# Generated by Django 4.0.1 on 2022-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_city_alter_users_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_user_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
