# Generated by Django 3.2.8 on 2022-02-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_users_is_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
