# Generated by Django 4.0.1 on 2022-03-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contest_category_masterstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_category',
            name='parent_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
