# Generated by Django 4.0.1 on 2022-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contest_category_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_category',
            name='parent_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
