# Generated by Django 4.0.1 on 2022-03-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_ads',
            name='adv_header_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='global_ads',
            name='adv_sidebar2_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='global_ads',
            name='adv_sidebar_top_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
