# Generated by Django 4.0.1 on 2022-03-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_global_ads_adv_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_category',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
