# Generated by Django 4.0.1 on 2022-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contest_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_category',
            name='color',
            field=models.CharField(blank=True, error_messages={'unique': 'Category color has been already exist!'}, max_length=255, null=True, unique=True),
        ),
    ]
